version: '3.9'

services:
  server:
    restart: always
    build: .
    container_name: Backend-server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 3001:3001
    environment:
        PORT: 3000
        MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
  client:
    build: ./client
    ports: 
      - 3000:3000
    container_name: Mission_frontend
  mongodb:
    image: mongo
    container_name: Mongodb
    restart: always
    ports:
      - 27017:27017
  
     